edit_uri: ""
markdown_extensions:
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: false
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 3
repo_name: nahualito/wintermute
repo_url: https://github.com/nahualito/wintermute
site_name: Wintermute Operator Manual
site_url: "https://nahualito.github.io/wintermute/"
theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/wintermute_log.svg
  features:
    - content.code.copy
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: dark)"
      accent: cyan
      primary: black
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      accent: cyan
      primary: black
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
use_directory_urls: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
  - mkdocs-jupyter:
      include_source: true
  - gen-files:
      scripts:
        - gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md # CHANGED: Points to root file
  - section-index
